compatibility_date = "2022-02-21"
name = "my-worker-dev"
account_id = "bb52740eebd84555643c70dac3acf533"
workers_dev = true
main = "src/index.ts"
compatibility_flags = ["streams_enable_constructors"]
